#!/bin/bash
#
# Shell script to regenerate the stylesheet

. myPaths.sh

pushd .

cd $gitHome

echo Generating CSS
cd lookandfeel/src
lessc style.less > style.css
cd -

echo Generating strings
cd daft
cp ../lookandfeel/strings.yaml ./node_modules/siq-lookandfeel
./node_modules/.bin/component build --templatepath daft/templates --staticpath static --baseurl=//static
cp ../lookandfeel/src/style.css ./static/components/lookandfeel
cp -rf ../lookandfeel/src/img/* ./static/components/lookandfeel/img
cd -

cd dax
cp ../lookandfeel/strings.yaml ./node_modules/siq-lookandfeel
./node_modules/.bin/component build --templatepath dax/templates --staticpath static --baseurl=//static
cp ../lookandfeel/src/style.css ./static/components/lookandfeel
cp -rf ../lookandfeel/src/img/* ./static/components/lookandfeel/img
cd -

cd glad
cp ../lookandfeel/strings.yaml ./node_modules/siq-lookandfeel
./node_modules/.bin/component build --templatepath glad/templates --staticpath static --baseurl=//static
cp ../lookandfeel/src/style.css ./static/components/lookandfeel
cp -rf ../lookandfeel/src/img/* ./static/components/lookandfeel/img
cd -

popd
