#!/bin/bash
#
# Shell script to reset the environment after a code get and perform all the install steps
# $1 would identify cacheClean mode. if clean  then clean cache otherwise assume it to be a project name.

if [ "$1" == 'clean' ]; then
	npm cache clean csi
	npm cache clean gloss
	npm cache clean siq-lookandfeel
	npm cache clean siq-mesh
	npm cache clean dax
	npm cache clean auxl
	npm cache clean siq-vendor-js
	npm cache clean bedrockjs
fi

. myPaths.sh

pushd .
cd $gitHome
 
function setup  {
	#Save folder context for later pop
	pushd .
	
	echo working project set to "$1"
	cd $1
	if [ $? -ne 0 ]; then
		echo 'Error locating project, ensure that you are launching from the folder where project is cloned'
		exit 1
	fi

	# remove node modules/ they will be setup again
	mkdir -p node_modules &> /dev/null
	cd node_modules
	if [ $? -ne 0 ]; then exit 1; fi
	rm -rf *
	cd -

	#remove static components
	mkdir -p static/components &> /dev/null
	cd static/components
	if [ $? -ne 0 ]; then exit 1; fi
	rm -rf *
	cd -

	echo Baking bindings for /static/components/models/explorers/1.0
	mkdir -p static/components/models/explorers/1.0 &> /dev/null
	cd $gatewayHome
	if [ $? -ne 0 ]; then exit 1; fi
	bake -m mesh.tasks mesh.javascript bundle=local.gateway.api.bundles.EXPLORERS_API version=[1,0] path=$projRPath$1"/static/components/models/explorers/1.0"
	cd -

	echo Baking bindings for /static/components/models/security/1.0
	mkdir -p static/components/models/security/1.0 &> /dev/null
	cd ../bastion
	if [ $? -ne 0 ]; then exit 1; fi
	bake -m mesh.tasks mesh.javascript bundle=bastion.security.bundle version=[1,0] path="../"$1"/static/components/models/security/1.0"
	cd -
	
	if [ "$1" == 'daft' ]; then		
		echo Baking bindings for /static/components/models/enamel/1.0
		mkdir -p static/components/models/infosets/1.0 &> /dev/null
		cd ../enamel
		if [ $? -ne 0 ]; then exit 1; fi
		bake -m mesh.tasks mesh.javascript bundle=enamel.component.API version=[1,0] path="../"$1"/static/components/models/enamel/1.0"
		cd -
	fi
	
	npm install
	./node_modules/.bin/component build --templatepath $1"/templates" --staticpath static

	popd
}

for i in "$@"
do
	if [ "$i" == 'clean' ]; then
		echo $i
	else
		setup $i
	fi
done

popd
